spring.application.name=my-blog-back-app-spring-boot

spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=root
# root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jackson.deserialization.fail-on-invalid-subtype=false